version: "3.4"

services:
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    # ports:
    #  - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # ports:
    #  - 9090:9090
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    volumes:
    - ./prometheus:/etc/prometheus
    - prometheus-db:/prometheus
    - ./prometheus/alert.rules:/alertmanager/alert.rules
    depends_on:
    - cadvisor
    - node-exporter
    - alertmanager

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    # ports:
    #  - 9100:9100
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.22.2
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    # ports:
    # - 9093:9093
    restart: unless-stopped


  grafana:
    image: grafana/grafana
    ports:
    - 4000:3000
    volumes:
    - grafana-db:/var/lib/grafana
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    user: "472"
    depends_on:
    - prometheus
  pushgateway:
    image: prom/pushgateway
    ports:
    - 9091:9091
    restart: always

volumes:
  grafana-db:
  prometheus-db:
  portainer-db:
